data:
  module: MNISTDataModule
  dataset:
    binary: 0
    polarity: bipolar
  loader:
    batch_size: 64
    num_workers: 16
    shuffle: 1

model:
  type: GAN
  discriminator:
    type: ConvEncoder
    args:
      channels: [64, 64, 64]
      dilation: [1, 1, 1]
      stride: [2,2,2]
      kernel_size: [5,5,5]
      norm: instance 
      nn_lin: LeakyReLU
      bias: False
  generator:
    type: DeconvEncoder
    args: 
      channels: [64, 64, 64]
      dilation: [1, 1, 1]
      stride: [2,2,2]
      kernel_size: [5,5,5]
      norm: batch
      bias: False
      nn_lin: LeakyReLU
      out_nnlin: Tanh
      #reshape_method: none
  latent:
    dim: 128
    dist: Normal
  training:
    balance: [5, 1]
    margin: 0.1
    invert: 0
    mode: wasserstein
    wgan_clip: 1.e-2
    gp: 10.0
    #feature_matching: 10.0
    lr: [5.e-5, 5.e-5]
    save:
      path: &dir /slow-1/axel/active_divergence/mnist
      name: &name mnist-wgan

callbacks:
  [
    { type: LearningRateMonitor, args: {logging_interval: "epoch"} },
    { type: ModelSummary, args: {max_depth: 1} },
    { type: ModelCheckpoint, args: {dirpath: *dir, filename: *name, every_n_epochs: 1, save_last: True, epoch_period: 10} },
    { type: DissectionMonitor, args: {monitor_epochs: 1, embedding_epochs: 10} },
    { type: ImgReconstructionMonitor }
  ]

