name: ??
rundir: "${dir:runtime}/saves/${name}"

hydra:
  job:
    name: "${name}"
  run:
    dir: "${rundir}"
  sweep:
    dir: "${dir:runtime}/saves/${name}"
    subdir: "${base:${data.dataset.root}}"

defaults:
  - data:
    - defaults
  - model: 
    - progressive_gan
  - _self_

data:
  dataset:
    sr: 16000
    bitrate: 16
    min_length: 80000
    sequence:
      length: 64
      mode: random
      idx: -2
  transforms:
    name: stft1024_16k
    force: 1
    pre_transforms:
      - {type: Mono, args: {squeeze: 1}}
      - {type: STFT, args: {nfft: 1024, hop_size: 256}}
    transforms:
      - {type: PolarMelInst, args: {mag_options : {nfft: 513, sample_rate: 16000, contrast: log, normalize: {mode: bipolar}},
                                    phase_options: {normalize: {mode: bipolar}},
                                    keep_nyquist: False}}

model:
  discriminator:
    args:
      norm: none
      channels: [64,128,256,512]
      kernel_size: 5
      stride: 1
  generator:
    args:
      norm: none
      channels: [64,128,256,512]
      kernel_size: 5
      stride: 1
      out_nnlin: Tanh
  latent:
    dim: 128
    dist: Normal
    concat_metadata: {pitch: {dim: 12, type: int, idx: -3 }}
  training:
    #training_schedule: [100,300,500]
    #transition_schedule: [150,250,400]
    training_schedule: [2,2,2]
    transition_schedule: [1,1,1]
    mode: wasserstein
    gp: 10.0

pl_trainer:
  max_epochs: 1e5
  gpus: [0]
  limit_train_batches: 1
  limit_val_batches: 1

callbacks:
  - { type: LearningRateMonitor, args: {logging_interval: "epoch"} }
  - { type: ModelSummary, args: {max_depth: 1} }
#  - { type: ModelCheckpoint, args: {dirpath: "${hydra:run.dir}", filename: "${hydra:job.name}", every_n_epochs: 100, save_last: True}
#  - { type: DissectionMonitor, args: {monitor_epochs: 10, embedding_epochs: 10, n_batches: 1, batch_size: 8} }
  - { type: AudioReconstructionMonitor, args: {plot_reconstructions: 1, plot_samples: 1, generate_files: 1, generate_samples: 1, generate_after_n_epochs: 7}}