name: ??
rundir: "${dir:runtime}/saves/${name}"

hydra:
  job:
    name: "${name}"
  run:
    dir: "${rundir}"
  sweep:
    dir: "${dir:runtime}/saves/${name}"
    subdir: "${base:${data.dataset.root}}"

defaults:
  - data:
    - defaults
    - dataset/audio
    - transforms/dgt-1024
  - model: 
    - progressive_gan
  - _self_

data:
  dataset:
    sr: 16000
    bitrate: 16
    min_length: 80000
    sequence:
      length: 256
      mode: start
      idx: -2
  transforms:
    name: stft1024_16k
    pre_transforms:
      - {type: Mono, args: {mode: left, squeeze: 1}}
      - {type: STFT, args: {n_fft: 1024, hop_length: 256}}
    transforms:
      - {type: PolarIF, args: {magnitude_mode: bipolar, phase_mode: bipolar, keep_nyquist: False}}
      - {type: Transpose, args: {dims: [-2, -3]}}
    augmentations:
      - {type: Shift, args: {prob: 0.3}}
      - {type: Amplitude, args: {prob: 0.5}}
  loader:
    batch_size: 64
    shuffle: True

model:
  discriminator:
    args:
      norm: none
      channels: [64,128,256,512]
      kernel_size: 5
      stride: 1
      multi_preconv: True
  generator:
    args:
      norm: none
      channels: [512,256,128,64]
      kernel_size: 5
      stride: 1
      out_nnlin: Tanh
      multi_preconv: True
  latent:
    dim: 128
    dist: Normal
    concat_metadata: {pitch: {dim: 12, type: int, idx: -3 }}
  training:
    #training_schedule: [100,300,500]
    #transition_schedule: [150,250,400]
    balance: [1, 1]
    margin: 0.1
    invert: 0
    lr: [1.e-4, 1.e-4]
    phase_at_init: 3
    transition_at_init: 0
    training_schedule: [2,2,2]
    transition_schedule: [1,1,1]
    mode: hinge 
    r1: 0.0
    #gp: 10.0

pl_trainer:
  max_epochs: 1e5
  # limit_train_batches: 1
  # limit_val_batches: 1

callbacks:
  - { type: LearningRateMonitor, args: {logging_interval: "epoch"} }
  - { type: ModelSummary, args: {max_depth: 1} }
#  - { type: ModelCheckpoint, args: {dirpath: "${hydra:run.dir}", filename: "${hydra:job.name}", every_n_epochs: 100, save_last: True}
#  - { type: DissectionMonitor, args: {monitor_epochs: 10, embedding_epochs: 10, n_batches: 1, batch_size: 8} }
  - { type: AudioReconstructionMonitor, args: {plot_reconstructions: 1, plot_samples: 1, generate_files: 1, generate_samples: 0, generate_after_n_epochs: 0}}
