name: ??
rundir: "${dir:runtime}/saves/${name}"

hydra:
  job:
    name: "${name}"
  run:
    dir: "${rundir}"
  sweep:
    dir: "${dir:runtime}/saves/${name}"
    subdir: "${base:${data.dataset.root}}"

defaults:
  - data:
    - defaults
    - dataset/audio
    - transforms/dgt-1024
  - model: 
    - dcgan
    - training/gan_adv
  - callbacks: audio_defaults
  - _self_

data:
  dataset:
    sr: 16000
    bitrate: 16
    sequence:
      length: 128
      mode: start 
      idx: -2
  transforms:
    name: dgt-512-magmel
    force: 0
    pre_transforms:
      - {type: Mono, args: {squeeze: 1}}
      - {type: STFT, args: {n_fft: &n_fft 512, hop_length: 128}}
      - {type: Magnitude, args: {contrast: log1p, n_fft: *n_fft, mel: 1, mode: unipolar}}
    transforms:
      - {type: Unsqueeze, args: {dim: -2}}
  loader:
    batch_size: 32

model:
  discriminator:
    args:
      norm: none
      channels: [64,128,256,512]
      kernel_size: 5
      stride: 2
      out_nnlin: Sigmoid
  generator:
    args:
      norm: none
      channels: [64,128,256,512]
      kernel_size: 5
      stride: 2
      out_nnlin: Tanh
  latent:
    dim: 128
    dist: Normal

pl_trainer:
  max_epochs: 1e5
  #limit_train_batches: 1
  #limit_val_batches: 1


callbacks:
  - { type: LearningRateMonitor, args: {logging_interval: "epoch"} }
  - { type: ModelSummary, args: {max_depth: 1} }
  - { type: ModelCheckpoint, args: {dirpath: "${hydra:run.dir}", filename: "${hydra:job.name}", every_n_epochs: 1, save_last: True, epoch_schedule: [0, 1, 2, 3, 5, 10, 15, 20, 25, 30, 35, 40, 50]} }
  - { type: DissectionMonitor, args: {monitor_epochs: 10, embedding_epochs: 10, n_batches: 5, batch_size: 512} }
  - { type: AudioReconstructionMonitor, args: {plot_reconstructions: 1, plot_samples: 1, generate_files: 1, generate_samples: 1}}
