name: ??
rundir: "${dir:runtime}/saves/${name}"
num_workers: 46

hydra:
  job:
    name: "${name}"
  run:
    dir: "${rundir}"
  sweep:
    dir: "${dir:runtime}/saves/${name}"
    subdir: "${base:${data.dataset.root}}"

defaults:
  - data:
    - defaults
  - model: 
    - dcgan
    - training/gan_wasserstein
  - callbacks: audio_defaults
  - _self_

data:
  dataset:
    sr: 16000
    bitrate: 16
    sequence:
      length: 16384
      mode: random
      idx: -1
  transforms:
    force: 0
    name: resampled_16k
    pre_transforms:
      - {type: Mono, args:{mode: left}}
  augmentations:
    - {type: Dequantize}
  loader:
    num_workers: "${num_workers}"

model:
  discriminator:
    input_augmentations: 
      - {type: PhaseShuffle, args: {dim: -1}}
    args:
      norm: none
      channels: [64,128,256,512,1024]
      kernel_size: 25
      stride: 4
  generator:
    args:
      norm: none
      channels: [64,128,256,512,1024]
      kernel_size: 25
      stride: 4
      out_nnlin: Tanh

  latent:
    dim: 128
    dist: Normal
  training:
    mode: wasserstein
    gp: 10.0

pl_trainer:
  max_epochs: 1e5
  gpus: [2]
  limit_train_batches: 1
  limit_val_batches: 1

