data:
  module: AudioDataModule
  dataset:
    root: /fast-1/datasets/acidsInstruments-ordinario
    sr: 44100
    sequence:
      length: 6144
      idx: -1
  transforms: 
    transforms: [{type: Mono, args:{squeeze: 1}}] 
  loader:
    batch_size: 128

model:
  type: Inversion
  transforms: [{type: Mono},
              {type: STFT, args: {nfft: 1024, hop_size: 512}},
              {type: Magnitude, args:{contrast: log, normalize: {mode: minmax, scale: unipolar}}}]
  inversion:
    type: MCNN
    args:
      kernel_size: 13
  training:
    lr: 1.e-5
    save:
      path: saves/
      name: test
  losses: 
    [
      {type: "SpectralLoss", args: {losses: {'mag_l2': {}}}}
    ]


callbacks:
  [
    { type: DissectionMonitor },
    { type: ImgReconstructionMonitor }
  ]

plugins:
  [
    { type: ADCheckpointIO }
  ]