data:
  module: AudioDataModule
  dataset:
    root: tests/acidsInstruments-test
    sr: 44100
    bitrate: 8
    target_length: &target_length 4.0
    active_tasks: [pitch, octave, dynamics]
    sequence:
      mode: random
      length: 65536
      idx: -1
  transforms: [ {type: Unsqueeze, args: {dim: -2}} ]
  augmentations:
    [
      {type: RandomPhase, args: {prob: 0.8}},
      {type: Dequantize}
    ]
  loader:
    batch_size: 64
    num_workers: 16
    shuffle: 1

model:
  type: RAVE
  training:
    lr: 1.e-4
    beta: 1.0
    warmup: 0
    save:
      path: &dir tests
      name: &name rave

callbacks:
  [
    { type: LearningRateMonitor, args: {logging_interval: "epoch"} },
    { type: ModelSummary, args: {max_depth: 1} },
    { type: ModelCheckpoint, args: {dirpath: *dir, filename: *name, every_n_epochs: 1, save_last: True, epoch_period: 10} },
    { type: DissectionMonitor, args: {monitor_epochs: 1, embedding_epochs: 10} },
    { type: AudioReconstructionMonitor }
  ]
