data:
  module: AudioDataModule
  dataset:
    root: /fast-1/datasets/acidsInstruments-ordinario
    sr: 44100
    check_folder: 0
    flatten: -2
#    sequence: 
#      length: 1
#      idx: -2
  transforms:
    force: 0
    name: stft-1024
    pre_transforms: [{type: Mono, args: {squeeze: 1}},
                     {type: STFT, args: {nfft: 1024, hop_size: 256}}]
                     #{type: NSGT, args: {bins: 96, ls: *target_length, downsample: 10}}]
    transforms: [{type: Magnitude, args:{contrast: log, normalize: {mode: gaussian, scale: unipolar}}},
                 {type: Unsqueeze, args: {dim: -2}}]
  loader:
    batch_size: 64
    num_workers: 16
    shuffle: 1

model:
  type: GAN
  generator:
    type: AutoEncoder
    external:
      path: /slow-1/axel/active_divergence/ordinario-vae/last.ckpt
      method: reinforce
      mode: forward
  discriminator:
    type: MLPEncoder
    args:
      dims: [512,256]
      dropout: 0.2
      norm: batch
      nnlin: LeakyReLU
      out_nnlin: Sigmoid
  latent:
    dim: 128
    dist: Normal
  training:
    balance: [1, 5]
    margin: 0.0
    invert: 0
    lr: [1.e-5, 1.e-5]
    mode: hinge
    save:
      path: &dir /slow-1/axel/active_divergence/mnist
      name: &name mnist-gan

callbacks:
  [
    { type: LearningRateMonitor, args: {logging_interval: "epoch"} },
    { type: ModelSummary, args: {max_depth: 1} },
    { type: ModelCheckpoint, args: {dirpath: *dir, filename: *name, every_n_epochs: 1, save_last: True, epoch_period: 10} },
    { type: DissectionMonitor, args: {monitor_epochs: 1, embedding_epochs: 10} },
    { type: ImgReconstructionMonitor }
  ]
